### ISSUE TITLE
[Enhancement] Enable GitHub Discussions

### ISSUE THREAD

**Issue by lprimak** [apache/shiro#2036]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

I have started a thread on the mailing list whether we should enable GH Discussions.

Email from Infra below:

---

Projects that are using GitHub Discussions and have suddenly found that feature to be missing, please see https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#repo_features

GitHub Discussions are now managed entirely through .asf.yaml, and will default to being disabled unless enabled in your .asf.yaml file, OR if you do not have a valid 'discussions' entry in your notifications section in the configuration.

The TL;DR for enabling Discussions in .asf.yaml is to weave these settings into your .asf.yaml file in your default branch:

```
notifications:
 discussions: [issues@foo.apache.org](mailto:issues@foo.apache.org)  (use your own mailing list here)
...
github:
 features:
   discussions: true
```

### Describe the solution you'd like

Described above

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!
